import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';

const notoSansKr = Noto_Sans_KR({
  weight: ['400', '500', '700'],
  display: 'swap',
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      {/* bg-slate-200 임시로 해놨습니다. */}
      <body className={`${notoSansKr.className} antialiased bg-slate-200`}>
        <div className="w-full max-w-[375px] lg:max-w-[1440px] mx-auto transition-all duration-300 ease-in-out">
          {children}
        </div>
      </body>
    </html>
  );
}
